spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://192.168.1.105:3306/char_room?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis配置
  redis:
    host: 192.168.1.105
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

#打印SQL
logging:
  level:
    com.miser.little.mapper : debug
#打印耗时
logTime: true

#密码加密
aes:
  key: abcdefgabcdefg12


